#12
stephenhadi/BlueTape pull request #27
Opened 2020-11-21 07:56 UTC by stephenhadi

Di perubahan kelas, ditambahkan jam selesai dari kuliah

2020-11-23 03:13 UTC, pascalalfadian commented
Hi Stephen. Karena sudah memasuki masa kuliah, saya tidak akan sempat mereview satu per satu MR nya di luar jam bimbingan. Mohon nanti ingatkan saja ya saat bimbingan, untuk melihat seluruh MR kamu.

2020-11-26 07:17 UTC, pascalalfadian commented
Mohon tambahkan juga di halaman cetak. Jika jam selesai tidak diisi, seperti tampilan saat ini. Jika jam selesai diisi, tampilkan hh:mm - hh:mm

2020-12-10 07:16 UTC, pascalalfadian requested changes
Mohon lihat 2 feedback saya.

2020-12-10 07:16 UTC, pascalalfadian commented on www/application/controllers/PerubahanKuliahRequest.php
> +                $finishTime = $this->input->post('timeFinish');
Mohon diseragamkan namanya: `'toDateTimeFinish'`, `$toDateTimeFinish`

2020-12-10 07:16 UTC, pascalalfadian commented on www/application/views/PerubahanKuliahRequest/main.php
> +                                <input class="form-control disableable timeFinish" type = "text" id="timepicker" name="timeFinish[]" />
Termasuk juga `id`, jangan gunakan `'timepicker;`, karena ini tentang `toFinishTime` bukan sekedar time picker.

2020-12-11 01:18 UTC, stephenhadi commented
@pascalalfadian Pak untuk issue ini diminta untuk diperiksa sebelum bimbingan berikutnya. Terima kasih

2020-12-14 03:21 UTC, pascalalfadian commented
Makasih. Tolong diperbaiki sedikit lagi, di detail permohonan, itu antara `-` dan jam berakhir harusnya ada spasi: 
[Screen Shot 2020-12-14 at 10 16 32](https://user-images.githubusercontent.com/5976057/102036674-03353580-3df6-11eb-9d84-102b86fe7517.png).

2020-12-14 04:56 UTC, stephenhadi commented
@pascalalfadian Pak sudah saya perbaiki bagian tersebut. Terima kasih.

2020-12-14 06:52 UTC, pascalalfadian approved these changes

2020-12-14 06:52 UTC, pascalalfadian commented
Sipp.. Makasih. Saya merge ya.

2020-12-14 06:52 UTC, merged