perbaikan setelah testing
stephenhadi/BlueTape pull request #34
Opened 2021-02-08 16:19 UTC by stephenhadi

2021-02-08 16:20 UTC, stephenhadi commented on www/application/controllers/PerubahanKuliahRequest.php
> +                        if($dateTimes[$i]!=''){
penambahan if karena jika "Diganti" atau "tambahan" dan input field dikosongkan akan menghasilkan error pada printview

2021-02-08 16:24 UTC, stephenhadi commented on www/application/views/EntriJadwalDosen/main.php
> +                                echo"<td align='center' id='cell" . $cellRowID . "-" . $cellColID . "' style='word-wrap:break-word;max-width: 8em'>" . "</td>";
kolom yang berisi text yang tidak memiliki spasi seperti "KKKKKKKKKKKKKKK" akan mengabaikan width:18% diatas, sehingga harus ditambahkan style ini

2021-02-09 09:06 UTC, pascalalfadian requested changes

2021-02-09 09:06 UTC, pascalalfadian commented on www/application/views/EntriJadwalDosen/main.php
> +                                echo"<td align='center' id='cell" . $cellRowID . "-" . $cellColID . "' style='word-wrap:break-word;max-width: 8em'>" . "</td>";
Haha kalau ada dosen yang tulis seperti itu, dosennya yang harus ditegur.

2021-02-09 09:06 UTC, pascalalfadian commented on www/application/controllers/PerubahanKuliahRequest.php
> +                        if($dateTimes[$i]!=''){
Noted, trims. Untuk if nya, mungkin gunakan ini aja, lebih aman:

```php
 if(!empty($dateTimes[$i])){  
```

2021-02-09 09:06 UTC, pascalalfadian commented
Hi @stephenhadi. Satu feedback aja, dan kalau udah oke langsung dimerge aja ya.

Trims.

2021-02-10 05:54 UTC, pascalalfadian approved these changes

2021-02-10 05:54 UTC, merged